/**
 * CSS custom properties from a DTCG export. Spec:
 * docs/superpowers/specs/2026-09-08-repository-delivery-design.md, section 5.
 *
 * A projection of a projection: it reads the DtcgExport, never the artifact,
 * and feeds no hash. What CSS cannot state is omitted and reported, never
 * approximated. Sets and each modifier's default context land at the root
 * selector, other contexts under a selector template; a mode's name never
 * chooses a media query.
 */
import { dtcgSlug, type DtcgExport, type DtcgJson, type DtcgTree } from '../dtcg';
import { compareCodeUnits } from '../diagnostics';
import { canonicalNumber } from '../precision';
import { scopesStateNumber } from '../units';
import {
  resolveNames, sortReport,
  type NameCase, type OutputMapEntry, type OutputReportEntry,
} from './naming';

export interface CssOutputOptions {
  case?: NameCase;
  /** Selector for sets and default contexts. */
  root?: string;
  /** Template for non-default contexts; `{mode}` and `{collection}` are replaced by their file-name slugs. */
  modeSelector?: string;
  /** Per-collection template, keyed by the resolver's collection label. */
  modes?: Record<string, string>;
}
export interface CssMapEntry extends OutputMapEntry { file: string }
export interface CssOutput { files: Record<string, string>; map: Record<string, CssMapEntry>; report: OutputReportEntry[] }
export const CSS_INDEX_FILE = 'index.css';
export interface OutputHeader { libraryId: string; contentHash: string; platform: string; format: string }

export const CSS_DEFAULTS: { case: NameCase; root: string; modeSelector: string } = {
  case: 'kebab', root: ':root', modeSelector: '[data-theme="{mode}"]',
};
/** The first bytes of every file this output writes; the CLI refuses to overwrite a file without them. */
export const CSS_HEADER_PREFIX = '/* Generated by spec-layer';
const EXT = 'com.spec-layer';

const CUSTOM_PROPERTY = /^--[A-Za-z0-9_-]+$/;
const BARE_IDENT = /^[A-Za-z_][A-Za-z0-9_-]*$/;

/** A declared WEB identifier as a custom property name, or null when it is not one. */
export function acceptCssDeclared(declared: string): string | null {
  if (CUSTOM_PROPERTY.test(declared)) return declared;
  if (BARE_IDENT.test(declared)) return `--${declared}`;
  return null;
}

// ---------------------------------------------------------------------------
// Reading the export
// ---------------------------------------------------------------------------

interface Leaf { path: string; type: string; value: DtcgJson; ext: DtcgTree | null }

const asRecord = (v: DtcgJson | undefined): DtcgTree | null =>
  (typeof v === 'object' && v !== null && !Array.isArray(v) ? v : null);

function collectLeaves(tree: DtcgJson, prefix: string[], out: Leaf[]): void {
  const node = asRecord(tree);
  if (!node) return;
  if ('$value' in node) {
    const ours = asRecord(asRecord(node.$extensions)?.[EXT]);
    out.push({
      path: prefix.join('.'), type: typeof node.$type === 'string' ? node.$type : '',
      value: node.$value, ext: ours,
    });
    return;
  }
  // Trees arrive key-sorted from sortTree, so this walk is deterministic.
  for (const key of Object.keys(node)) {
    if (key.startsWith('$')) continue;
    collectLeaves(node[key], [...prefix, key], out);
  }
}

export interface CssSource { collection: string; mode: string | null; file: string; isDefault: boolean }
type Source = CssSource;

const unpointer = (s: string): string => s.replace(/~1/g, '/').replace(/~0/g, '~');
const refFile = (src: DtcgJson): string | null => {
  const r = asRecord(src);
  return r && typeof r.$ref === 'string' ? r.$ref : null;
};

/** Every file the resolver names, in resolution order, with what it stands for. */
function sourcesOf(resolver: DtcgExport['resolver']): Source[] {
  const out: Source[] = [];
  for (const { $ref } of resolver.resolutionOrder) {
    const set = /^#\/sets\/(.+)$/.exec($ref);
    const mod = /^#\/modifiers\/(.+)$/.exec($ref);
    if (set) {
      const label = unpointer(set[1]);
      for (const src of resolver.sets[label]?.sources ?? []) {
        const file = refFile(src);
        if (file) out.push({ collection: label, mode: null, file, isDefault: true });
      }
    } else if (mod) {
      const label = unpointer(mod[1]);
      const m = resolver.modifiers[label];
      if (!m) continue;
      // A modifier with no default has no context at the root: emitting one
      // would choose a mode Figma did not state.
      for (const [context, srcs] of Object.entries(m.contexts)) {
        for (const src of srcs) {
          const file = refFile(src);
          if (file) out.push({ collection: label, mode: context, file, isDefault: context === m.default });
        }
      }
    }
  }
  return out;
}

/** `primitives.light-2.json` -> `light-2`: the mode part of the file name the DTCG projection chose. */
const modeSlug = (file: string): string => file.replace(/\.json$/, '').split('.').slice(1).join('.');
const collectionSlug = (file: string): string => file.split('.')[0];

/**
 * The CSS file each DTCG source file writes: a set by its resolver label, a
 * modifier context with the DTCG file's mode slug appended. index.css is
 * reserved; a taken name gets -2, -3, ... in source order, as fileNameFor does.
 * Spec section 3.
 */
export function cssFileNames(sources: CssSource[]): Map<string, string> {
  const taken = new Set<string>([CSS_INDEX_FILE]);
  const out = new Map<string, string>();
  for (const s of sources) {
    if (out.has(s.file)) continue;
    const base = s.mode === null ? dtcgSlug(s.collection) : `${dtcgSlug(s.collection)}.${modeSlug(s.file)}`;
    let candidate = `${base}.css`;
    let n = 1;
    while (taken.has(candidate)) {
      n += 1;
      candidate = `${base}-${n}.css`;
    }
    taken.add(candidate);
    out.set(s.file, candidate);
  }
  return out;
}

// ---------------------------------------------------------------------------
// Values
// ---------------------------------------------------------------------------

/**
 * `names` is the permanent assignment from `resolveNames` (a missing path
 * collided and was reported); `alive` is this fixed-point pass's declared
 * paths, which references are checked against. Every non-collided leaf is
 * attempted every pass, so the stable pass reports each omission afresh.
 */
interface Ctx {
  names: Map<string, string>; alive: Set<string>; report: OutputReportEntry[]; path: string; mode?: string;
  /** Whether the path's own Figma scopes state a unitless number (`OPACITY`,
   *  `FONT_WEIGHT`); a DTCG leaf cannot say, and the remedy depends on it. */
  statesNumber: boolean;
}

const REF = /^\{(.+)\}$/;

function hexChannels(hex: string): [number, number, number] {
  const at = (i: number) => parseInt(hex.slice(i, i + 2), 16);
  return [at(1), at(3), at(5)];
}
const quoteFamily = (f: string): string => `"${f.replace(/["\\]/g, '\\$&')}"`;

function report(ctx: Ctx, entry: Omit<OutputReportEntry, 'path' | 'mode'>): void {
  ctx.report.push({ ...entry, path: ctx.path, ...(ctx.mode !== undefined ? { mode: ctx.mode } : {}) });
}

/** One CSS value, or null when omitted and reported. `property` names a style member. */
function cssValue(ctx: Ctx, type: string, value: DtcgJson, property?: string): string | null {
  const member: Record<string, DtcgJson> = property !== undefined ? { property } : {};
  if (typeof value === 'string') {
    const ref = REF.exec(value);
    if (ref) {
      const name = ctx.alive.has(ref[1]) ? ctx.names.get(ref[1]) : undefined;
      if (name !== undefined) return `var(${name})`;
      report(ctx, {
        code: 'reference_target_omitted', severity: 'warning',
        message: `References ${ref[1]}, which this output does not emit; the value was omitted.`,
        details: { target: ref[1], ...member },
      });
      return null;
    }
  }
  switch (type) {
    case 'color': {
      if (typeof value === 'string') return value; // legacy `#rrggbb` or `#rrggbbaa`, verbatim
      const c = asRecord(value);
      if (c && typeof c.hex === 'string' && typeof c.alpha === 'number') {
        if (c.alpha === 1) return c.hex;
        const [r, g, b] = hexChannels(c.hex);
        return `rgb(${r} ${g} ${b} / ${c.alpha})`;
      }
      break;
    }
    case 'dimension':
    case 'duration': {
      if (typeof value === 'string') return value;
      const d = asRecord(value);
      if (d && typeof d.value === 'number' && typeof d.unit === 'string') return `${d.value}${d.unit}`;
      break;
    }
    case 'fontWeight':
      if (typeof value === 'number') return String(value);
      break;
    case 'number':
      if (typeof value === 'number') {
        // CSS reads a bare number as a number, not a length (`height: 36` is
        // dropped). A typography style's `lineHeight` member is the exception:
        // its unit is per style (PIXELS arrives as a `dimension`), so a bare
        // number is a valid CSS multiplier. Every other number, including a
        // top-level LINE_HEIGHT-scoped variable, has no unit because the file
        // states none; it is emitted and reported, never given a unit.
        //
        // Two messages: a token whose scopes state nothing is missing a unit
        // (narrowing scopes is the fix, worded as in the file header); an
        // `OPACITY`/`FONT_WEIGHT` token states it has none, so telling its
        // owner to narrow scopes would be false. Both are reported, since
        // neither is a length.
        if (property !== 'lineHeight') {
          report(ctx, {
            code: 'unitless_number', severity: 'warning',
            message: ctx.statesNumber
              ? 'This token has no unit, because its Figma scopes state it is a unitless number. CSS reads it as a number, not a length, which is what those scopes ask for. Do not use it where a length is expected.'
              : 'This token has no unit, because its Figma variable states none. CSS reads it as a number, not a length. Narrow the variable\'s scopes in Figma and pull again.',
            details: { value, ...member },
          });
        }
        return String(value);
      }
      break;
    case 'cubicBezier':
      if (Array.isArray(value) && value.length === 4 && value.every((n) => typeof n === 'number')) {
        return `cubic-bezier(${value.join(', ')})`;
      }
      break;
    case 'fontFamily':
      if (typeof value === 'string') return quoteFamily(value);
      if (Array.isArray(value) && value.every((f) => typeof f === 'string')) {
        return (value as string[]).map(quoteFamily).join(', ');
      }
      break;
    default:
      break;
  }
  report(ctx, {
    code: 'not_expressible', severity: 'warning',
    message: `CSS has no form for this ${type || 'untyped'} value; it was omitted.`,
    details: { type, value, ...member },
  });
  return null;
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const TEXT_TRANSFORM: Record<string, string> = { original: 'none', upper: 'uppercase', lower: 'lowercase', title: 'capitalize' };
const TEXT_DECORATION: Record<string, string> = { none: 'none', underline: 'underline', strikethrough: 'line-through' };

/** `$value` members a typography leaf may carry, each its own custom property. */
const TYPOGRAPHY_MEMBERS: ReadonlyArray<readonly [key: string, type: string]> = [
  ['fontFamily', 'fontFamily'],
  ['fontSize', 'dimension'],
  ['fontWeight', 'fontWeight'],
  ['lineHeight', 'number'],
  ['letterSpacing', 'dimension'],
];
/** `$extensions` members resolved through a lookup table, keyed by their CSS-facing member name. */
const TEXT_MEMBERS: ReadonlyArray<readonly [key: string, extKey: string, table: Record<string, string>]> = [
  ['textTransform', 'textCase', TEXT_TRANSFORM],
  ['textDecoration', 'textDecoration', TEXT_DECORATION],
];
/**
 * The member keys one typography leaf registers names under: one per member it
 * will emit, by the conditions `typographyDecls` checks. A member path that
 * collides with a token path omits both, like two tokens. The style's own path
 * is never registered, and an absent member reserves no name, which could only
 * waste one or collide with a token that needed it.
 */
function typographyMemberKeys(value: DtcgTree, ext: DtcgTree): string[] {
  const keys: string[] = [];
  for (const [key] of TYPOGRAPHY_MEMBERS) {
    if (key in value) keys.push(key);
  }
  for (const key of ['lineHeight', 'letterSpacing'] as const) {
    if (key in value) continue; // already covered by the loop above
    const d = asRecord(ext[key]);
    if (d && typeof d.value === 'number' && typeof d.unit === 'string') keys.push(key);
  }
  for (const [key, extKey] of TEXT_MEMBERS) {
    if (typeof ext[extKey] === 'string') keys.push(key);
  }
  return keys;
}

function converted(ctx: Ctx, property: string, from: DtcgTree, to: string): void {
  report(ctx, {
    code: 'value_converted', severity: 'info',
    message: `${property} was restated from ${String(from.value)}${String(from.unit)} as ${to}.`,
    details: { property, from, to },
  });
}

/** A member the DTCG projection parked under $extensions because the format had no home for it. CSS does. */
function extensionDimension(
  ctx: Ctx, ext: DtcgTree, key: string, name: string, percentTo: (n: number) => string,
): string | null {
  const d = asRecord(ext[key]);
  if (!d || typeof d.value !== 'number' || typeof d.unit !== 'string') return null;
  if (d.unit === '%') {
    const to = percentTo(canonicalNumber(d.value / 100));
    converted(ctx, key, d, to);
    return `${name}: ${to};`;
  }
  return `${name}: ${d.value}${d.unit};`;
}

/**
 * Declarations for one typography leaf's members, plus the member paths
 * declared. `names` is keyed by `${leaf.path}.${memberKey}`; a member with no
 * name (collided or pruned) is skipped, since resolveNames reported it.
 */
function typographyDecls(
  ctx: Ctx, leaf: Leaf, names: Map<string, string>,
): { decls: string[]; declaredPaths: string[] } {
  const decls: string[] = [];
  const declaredPaths: string[] = [];
  const value = asRecord(leaf.value) ?? {};
  const ext = leaf.ext ?? {};
  const nameFor = (key: string): string | undefined => names.get(`${leaf.path}.${key}`);

  for (const [key, type] of TYPOGRAPHY_MEMBERS) {
    if (!(key in value)) continue;
    const name = nameFor(key);
    if (name === undefined) continue; // collided; already reported by resolveNames
    const css = cssValue(ctx, type, value[key], key);
    if (css !== null) { decls.push(`${name}: ${css};`); declaredPaths.push(`${leaf.path}.${key}`); }
  }
  // A px line height could not be a DTCG multiplier; CSS states px directly.
  // A % letter spacing is a fraction of the font size, which is what em means.
  if (!('lineHeight' in value)) {
    const name = nameFor('lineHeight');
    if (name !== undefined) {
      const d = extensionDimension(ctx, ext, 'lineHeight', name, (n) => String(n));
      if (d) { decls.push(d); declaredPaths.push(`${leaf.path}.lineHeight`); }
    }
  }
  if (!('letterSpacing' in value)) {
    const name = nameFor('letterSpacing');
    if (name !== undefined) {
      const d = extensionDimension(ctx, ext, 'letterSpacing', name, (n) => `${n}em`);
      if (d) { decls.push(d); declaredPaths.push(`${leaf.path}.letterSpacing`); }
    }
  }
  for (const [key, extKey, table] of TEXT_MEMBERS) {
    const raw = ext[extKey];
    if (typeof raw !== 'string') continue;
    const name = nameFor(key);
    if (name === undefined) continue; // collided; already reported by resolveNames
    const css = table[raw];
    if (css !== undefined) {
      decls.push(`${name}: ${css};`);
      declaredPaths.push(`${leaf.path}.${key}`);
    } else {
      report(ctx, {
        code: 'not_expressible', severity: 'info',
        message: `CSS text properties have no form for ${extKey} "${raw}"; it was omitted.`,
        details: { property: extKey, value: raw },
      });
    }
  }
  return { decls, declaredPaths };
}

const SHADOW_MEMBERS: Array<[key: string, type: string]> = [
  ['offsetX', 'dimension'], ['offsetY', 'dimension'], ['blur', 'dimension'], ['spread', 'dimension'], ['color', 'color'],
];

function shadowDecl(ctx: Ctx, leaf: Leaf, name: string): string | null {
  const layers = Array.isArray(leaf.value) ? leaf.value : [];
  const omit = (reason: string, message: string): null => {
    report(ctx, { code: 'not_expressible', severity: 'warning', message, details: { reason } });
    return null;
  };
  if (layers.length === 0) return omit('no_visible_shadow', 'The style has no visible shadow, so no box-shadow was written.');
  const parts: string[] = [];
  for (const layer of layers) {
    const l = asRecord(layer);
    if (!l) return omit('layer_not_an_object', 'A shadow layer is not an object; the style was omitted.');
    const members: string[] = [];
    for (const [key, type] of SHADOW_MEMBERS) {
      if (!(key in l)) return omit(`missing_${key}`, `A shadow layer has no ${key}, which box-shadow needs; the style was omitted.`);
      const css = cssValue(ctx, type, l[key], key);
      if (css === null) return null; // already reported by cssValue
      members.push(css);
    }
    parts.push(`${l.inset === true ? 'inset ' : ''}${members.join(' ')}`);
  }
  return `${name}: ${parts.join(', ')};`;
}

// ---------------------------------------------------------------------------
// The file
// ---------------------------------------------------------------------------

// Collection and mode names are free text: a comment terminator in one would
// turn the rest of the name into a live rule, and a line break would split it.
const commentSafe = (text: string): string => text.replace(/\*\//g, '* /').replace(/[\r\n]+/g, ' ');

/**
 * `unitlessCount`: distinct token paths in this file reported `unitless_number`;
 * a file with none keeps the two-line header byte for byte. Each is a token
 * whose Figma variable states no unit (OPACITY and FONT_WEIGHT scopes are
 * excluded upstream), so narrowing scopes is the right remedy for every one.
 * The report path follows the CLI's `outputId` (`packages/cli/src/outputs.ts`)
 * and is stated relative to the pull's output directory, which this layer does
 * not know.
 *
 * `derivedCount`: properties whose unit came from the library's stated usage;
 * naming the unitless ones but not the inferred ones would tell half the truth.
 * The line says "its own Figma variable does not state" because alias-scope
 * evidence is a scope, set on a token that aliases this one.
 */
function headerText(
  header: OutputHeader, nameCase: NameCase, unitlessCount = 0, derivedCount = 0,
): string {
  const lines = [
    `${CSS_HEADER_PREFIX} from library ${commentSafe(header.libraryId)}, foundation ${header.contentHash}, ${header.platform}/${header.format}/${nameCase}.`,
    '   Do not edit. Change the design in Figma, republish, and run spec-layer pull.',
  ];
  if (unitlessCount > 0) {
    const reportFile = `${header.platform}-${header.format}.report.json`;
    if (unitlessCount === 1) {
      lines.push(
        '   1 property in this file has no unit, because its Figma variable states none.',
        `   CSS reads it as a number, not a length. See outputs/${reportFile} under your pull's output directory, or narrow the variable's scopes in Figma.`,
      );
    } else {
      lines.push(
        `   ${unitlessCount} properties in this file have no unit, because their Figma variables state none.`,
        `   CSS reads them as numbers, not lengths. See outputs/${reportFile} under your pull's output directory, or narrow the variables' scopes in Figma.`,
      );
    }
  }
  if (derivedCount > 0) {
    lines.push(
      derivedCount === 1
        ? '   1 property in this file has a unit its own Figma variable does not state, taken from how the library uses the token.'
        : `   ${derivedCount} properties in this file have a unit their own Figma variables do not state, taken from how the library uses those tokens.`,
      `   See tokens/report.json under your pull's output directory for what pinned ${derivedCount === 1 ? 'it' : 'each one'}.`,
    );
  }
  return `${lines.join('\n')} */`;
}

interface Block { selector: string; comment: string; decls: string[] }
interface EmitResult {
  /** One block per DTCG source file that declared anything, in source order. */
  blocks: Map<string, Block>;
  entries: OutputReportEntry[];
  /** Every path (token, shadow, or typography member) that got a declaration this pass. */
  declared: Set<string>;
  /** The DTCG source file that first declared each path, in source order. */
  firstFile: Map<string, string>;
  /** DTCG source file -> token paths reported `unitless_number`, minus those
   *  whose own scopes state a unitless number. */
  unitlessByFile: Map<string, Set<string>>;
  /** DTCG source file -> token paths whose unit was derived from usage. */
  derivedByFile: Map<string, Set<string>>;
}

/** What `cssValue` cannot see: a DTCG leaf carries no scopes, so a `number`
 *  leaf cannot say whether it lacks a unit or states it has none. */
interface PathFacts {
  /** Paths whose Figma scopes state a unitless number (OPACITY, FONT_WEIGHT). */
  statesNumber: Set<string>;
  /** Paths the projection reported `unit_derived_from_usage` for. */
  derived: Set<string>;
}

/** One attempt at every block; a fixed-point retry calls it with a smaller `alive`. */
function emitPass(
  sources: Source[], leavesByFile: Map<string, Leaf[]>, names: Map<string, string>, alive: Set<string>,
  root: string, template: string, modes: Record<string, string> | undefined, facts: PathFacts,
): EmitResult {
  const entries: OutputReportEntry[] = [];
  const declared = new Set<string>();
  const firstFile = new Map<string, string>();
  const blocks = new Map<string, Block>();
  const unitlessByFile = new Map<string, Set<string>>();
  const derivedByFile = new Map<string, Set<string>>();
  const note = (by: Map<string, Set<string>>, file: string, path: string): void => {
    const set = by.get(file) ?? new Set<string>();
    set.add(path);
    by.set(file, set);
  };
  for (const s of sources) {
    const perCollection = modes?.[s.collection];
    const selector = s.isDefault ? root : (perCollection ?? template)
      .replace(/\{mode\}/g, modeSlug(s.file))
      .replace(/\{collection\}/g, collectionSlug(s.file));
    const decls: string[] = [];
    const declaredHere: string[] = [];
    for (const leaf of leavesByFile.get(s.file) ?? []) {
      const ctx: Ctx = {
        names, alive, report: entries, path: leaf.path,
        statesNumber: facts.statesNumber.has(leaf.path),
        ...(s.mode !== null ? { mode: s.mode } : {}),
      };
      if (leaf.type === 'typography') {
        const t = typographyDecls(ctx, leaf, names);
        decls.push(...t.decls);
        for (const p of t.declaredPaths) { declared.add(p); declaredHere.push(p); }
      } else {
        const name = names.get(leaf.path);
        if (name === undefined) continue; // collided; already reported by resolveNames
        if (leaf.type === 'shadow') {
          const d = shadowDecl(ctx, leaf, name);
          if (d !== null) { decls.push(d); declared.add(leaf.path); declaredHere.push(leaf.path); }
        } else {
          const before = entries.length;
          const v = cssValue(ctx, leaf.type, leaf.value);
          if (v !== null) { decls.push(`${name}: ${v};`); declared.add(leaf.path); declaredHere.push(leaf.path); }
          if (entries.length > before && entries[entries.length - 1].code === 'unitless_number'
            && !ctx.statesNumber) {
            note(unitlessByFile, s.file, leaf.path);
          }
          if (v !== null && facts.derived.has(leaf.path)) note(derivedByFile, s.file, leaf.path);
        }
      }
    }
    if (decls.length === 0) continue;
    for (const p of declaredHere) if (!firstFile.has(p)) firstFile.set(p, s.file);
    const comment = `/* ${commentSafe(`${s.collection}${s.mode !== null ? `, ${s.mode}` : ''}`)} */`;
    const existing = blocks.get(s.file);
    if (existing) existing.decls.push(...decls);
    else blocks.set(s.file, { selector, comment, decls });
  }
  return { blocks, entries, declared, firstFile, unitlessByFile, derivedByFile };
}

export function cssOutput(exp: DtcgExport, header: OutputHeader, options: CssOutputOptions = {}): CssOutput {
  const nameCase = options.case ?? CSS_DEFAULTS.case;
  const root = options.root ?? CSS_DEFAULTS.root;
  const template = options.modeSelector ?? CSS_DEFAULTS.modeSelector;
  const sources = sourcesOf(exp.resolver);

  const leavesByFile = new Map<string, Leaf[]>();
  for (const s of sources) {
    if (!leavesByFile.has(s.file)) {
      const out: Leaf[] = [];
      collectLeaves(exp.files[s.file] ?? {}, [], out);
      leavesByFile.set(s.file, out);
    }
  }

  // A typography leaf registers one path per emitted member, never its own (see
  // typographyMemberKeys); a shadow leaf, like a token, registers its path.
  const candidatePaths = new Set<string>();
  for (const leaves of leavesByFile.values()) {
    for (const leaf of leaves) {
      if (leaf.type === 'typography') {
        const value = asRecord(leaf.value) ?? {};
        const ext = leaf.ext ?? {};
        for (const key of typographyMemberKeys(value, ext)) candidatePaths.add(`${leaf.path}.${key}`);
      } else {
        candidatePaths.add(leaf.path);
      }
    }
  }

  const resolved = resolveNames([...candidatePaths], exp.meta, {
    codeSyntaxKey: 'WEB', acceptDeclared: acceptCssDeclared, affix: (body) => `--${body}`, nameCase,
  });
  const names = resolved.names; // permanent: a path missing here collided, and is done

  // What the DTCG leaves cannot state, read from the record that can.
  const facts: PathFacts = {
    statesNumber: new Set(Object.entries(exp.meta)
      .filter(([, entry]) => scopesStateNumber(entry.scopes))
      .map(([path]) => path)),
    derived: new Set(exp.report
      .filter((entry) => entry.code === 'unit_derived_from_usage')
      .map((entry) => entry.path)),
  };
  const emit = (alive: Set<string>) =>
    emitPass(sources, leavesByFile, names, alive, root, template, options.modes, facts);

  // Fixed point on which names a reference may resolve through: a name nothing
  // declares strands whatever references it, so shrink `alive` to what got
  // declared and retry. Each pass attempts every non-collided leaf, so the
  // stable pass carries a complete set of omission reports. Every var() then
  // has a declaration somewhere in the file, though not necessarily in its own
  // block, and a reference across selector blocks is still valid CSS.
  let alive = new Set(names.keys());
  let pass = emit(alive);
  for (;;) {
    if (pass.declared.size === alive.size) break;
    alive = pass.declared;
    pass = emit(alive);
  }

  const fileNames = cssFileNames(sources);
  const map: Record<string, CssMapEntry> = {};
  for (const [path, entry] of Object.entries(resolved.map)) {
    const from = pass.firstFile.get(path);
    if (alive.has(path) && from !== undefined) map[path] = { ...entry, file: fileNames.get(from) as string };
  }

  const entries: OutputReportEntry[] = [...resolved.report, ...pass.entries];

  const shared = [...new Set(sources
    .filter((s) => !s.isDefault && options.modes?.[s.collection] === undefined)
    .map((s) => s.collection))].sort(compareCodeUnits);
  if (shared.length > 1) {
    for (const collection of shared) {
      entries.push({
        code: 'mode_selector_shared', severity: 'warning', path: collection,
        message: `${shared.length} collections with modes share the selector template ${template}; one attribute cannot carry both axes. Declare a selector per collection under outputs[].modes.`,
        details: { modifiers: shared, selector: template },
      });
    }
  }

  const files: Record<string, string> = {};
  const imports: string[] = [];
  for (const [source, block] of pass.blocks) {
    const name = fileNames.get(source) as string;
    const head = headerText(
      header, nameCase,
      pass.unitlessByFile.get(source)?.size ?? 0,
      pass.derivedByFile.get(source)?.size ?? 0,
    );
    files[name] = `${head}\n\n${block.selector} {\n  ${block.comment}\n${block.decls.map((d) => `  ${d}`).join('\n')}\n}\n`;
    imports.push(block.comment, `@import "./${name}";`);
  }
  // index.css only imports, so it never carries the unitless note.
  if (imports.length > 0) files[CSS_INDEX_FILE] = `${headerText(header, nameCase)}\n\n${imports.join('\n')}\n`;
  return { files, map, report: sortReport(entries) };
}
