/**
 * CSS custom properties from a DTCG export. Spec:
 * docs/superpowers/specs/2026-09-08-repository-delivery-design.md, section 5.
 *
 * A projection of a projection: it reads the DtcgExport and never the
 * artifact, so v5 keeps one reader. It feeds no hash. Anything CSS cannot
 * state is omitted and reported, never approximated. Sets and every
 * modifier's default context land at the root selector; every other context
 * lands in a block under a declared selector template. Nothing about a
 * mode's name chooses a media query.
 */
import type { DtcgExport, DtcgJson, DtcgTree } from '../dtcg';
import { compareCodeUnits } from '../diagnostics';
import { canonicalNumber } from '../precision';
import {
  resolveNames, sortReport,
  type NameCase, type OutputMapEntry, type OutputReportEntry,
} from './naming';

export interface CssOutputOptions {
  case?: NameCase;
  /** Selector for sets and default contexts. */
  root?: string;
  /** Template for non-default contexts; `{mode}` and `{collection}` are replaced by their file-name slugs. */
  modeSelector?: string;
  /** Per-collection template, keyed by the resolver's collection label. */
  modes?: Record<string, string>;
}
export interface CssOutput { text: string; map: Record<string, OutputMapEntry>; report: OutputReportEntry[] }
export interface OutputHeader { libraryId: string; contentHash: string; platform: string; format: string }

export const CSS_DEFAULTS: { case: NameCase; root: string; modeSelector: string } = {
  case: 'kebab', root: ':root', modeSelector: '[data-theme="{mode}"]',
};
/** The first bytes of every file this output writes; the CLI refuses to overwrite a file without them. */
export const CSS_HEADER_PREFIX = '/* Generated by spec-layer';
const EXT = 'com.spec-layer';

const CUSTOM_PROPERTY = /^--[A-Za-z0-9_-]+$/;
const BARE_IDENT = /^[A-Za-z_][A-Za-z0-9_-]*$/;

/** A declared WEB identifier as a custom property name, or null when it is not one. */
export function acceptCssDeclared(declared: string): string | null {
  if (CUSTOM_PROPERTY.test(declared)) return declared;
  if (BARE_IDENT.test(declared)) return `--${declared}`;
  return null;
}

// ---------------------------------------------------------------------------
// Reading the export
// ---------------------------------------------------------------------------

interface Leaf { path: string; type: string; value: DtcgJson; ext: DtcgTree | null }

const asRecord = (v: DtcgJson | undefined): DtcgTree | null =>
  (typeof v === 'object' && v !== null && !Array.isArray(v) ? v : null);

function collectLeaves(tree: DtcgJson, prefix: string[], out: Leaf[]): void {
  const node = asRecord(tree);
  if (!node) return;
  if ('$value' in node) {
    const ours = asRecord(asRecord(node.$extensions)?.[EXT]);
    out.push({
      path: prefix.join('.'), type: typeof node.$type === 'string' ? node.$type : '',
      value: node.$value, ext: ours,
    });
    return;
  }
  // Trees arrive key-sorted from sortTree, so this walk is deterministic.
  for (const key of Object.keys(node)) {
    if (key.startsWith('$')) continue;
    collectLeaves(node[key], [...prefix, key], out);
  }
}

interface Source { collection: string; mode: string | null; file: string; isDefault: boolean }

const unpointer = (s: string): string => s.replace(/~1/g, '/').replace(/~0/g, '~');
const refFile = (src: DtcgJson): string | null => {
  const r = asRecord(src);
  return r && typeof r.$ref === 'string' ? r.$ref : null;
};

/** Every file the resolver names, in resolution order, with what it stands for. */
function sourcesOf(resolver: DtcgExport['resolver']): Source[] {
  const out: Source[] = [];
  for (const { $ref } of resolver.resolutionOrder) {
    const set = /^#\/sets\/(.+)$/.exec($ref);
    const mod = /^#\/modifiers\/(.+)$/.exec($ref);
    if (set) {
      const label = unpointer(set[1]);
      for (const src of resolver.sets[label]?.sources ?? []) {
        const file = refFile(src);
        if (file) out.push({ collection: label, mode: null, file, isDefault: true });
      }
    } else if (mod) {
      const label = unpointer(mod[1]);
      const m = resolver.modifiers[label];
      if (!m) continue;
      // A modifier with no default has no context at the root: emitting one
      // would choose a mode Figma did not state.
      for (const [context, srcs] of Object.entries(m.contexts)) {
        for (const src of srcs) {
          const file = refFile(src);
          if (file) out.push({ collection: label, mode: context, file, isDefault: context === m.default });
        }
      }
    }
  }
  return out;
}

/** `primitives.light-2.json` -> `light-2`: the mode part of the file name the DTCG projection chose. */
const modeSlug = (file: string): string => file.replace(/\.json$/, '').split('.').slice(1).join('.');
const collectionSlug = (file: string): string => file.split('.')[0];

// ---------------------------------------------------------------------------
// Values
// ---------------------------------------------------------------------------

/**
 * `names` is the permanent, never-shrinking assignment from `resolveNames`
 * (a path missing here collided and was already reported); `alive` is the
 * current fixed-point pass's set of paths that actually got a declaration,
 * and is what a reference is checked against. Every non-collided leaf is
 * still attempted every pass regardless of whether its own path is in
 * `alive`, so its own omission is freshly reported in whichever pass turns
 * out to be the stable one.
 */
interface Ctx {
  names: Map<string, string>; alive: Set<string>; report: OutputReportEntry[]; path: string; mode?: string;
}

const REF = /^\{(.+)\}$/;

function hexChannels(hex: string): [number, number, number] {
  const at = (i: number) => parseInt(hex.slice(i, i + 2), 16);
  return [at(1), at(3), at(5)];
}
const quoteFamily = (f: string): string => `"${f.replace(/["\\]/g, '\\$&')}"`;

function report(ctx: Ctx, entry: Omit<OutputReportEntry, 'path' | 'mode'>): void {
  ctx.report.push({ ...entry, path: ctx.path, ...(ctx.mode !== undefined ? { mode: ctx.mode } : {}) });
}

/** One CSS value, or null when omitted and reported. `property` names a style member. */
function cssValue(ctx: Ctx, type: string, value: DtcgJson, property?: string): string | null {
  const member: Record<string, DtcgJson> = property !== undefined ? { property } : {};
  if (typeof value === 'string') {
    const ref = REF.exec(value);
    if (ref) {
      const name = ctx.alive.has(ref[1]) ? ctx.names.get(ref[1]) : undefined;
      if (name !== undefined) return `var(${name})`;
      report(ctx, {
        code: 'reference_target_omitted', severity: 'warning',
        message: `References ${ref[1]}, which this output does not emit; the value was omitted.`,
        details: { target: ref[1], ...member },
      });
      return null;
    }
  }
  switch (type) {
    case 'color': {
      if (typeof value === 'string') return value; // legacy `#rrggbb` or `#rrggbbaa`, verbatim
      const c = asRecord(value);
      if (c && typeof c.hex === 'string' && typeof c.alpha === 'number') {
        if (c.alpha === 1) return c.hex;
        const [r, g, b] = hexChannels(c.hex);
        return `rgb(${r} ${g} ${b} / ${c.alpha})`;
      }
      break;
    }
    case 'dimension':
    case 'duration': {
      if (typeof value === 'string') return value;
      const d = asRecord(value);
      if (d && typeof d.value === 'number' && typeof d.unit === 'string') return `${d.value}${d.unit}`;
      break;
    }
    case 'number':
    case 'fontWeight':
      if (typeof value === 'number') return String(value);
      break;
    case 'cubicBezier':
      if (Array.isArray(value) && value.length === 4 && value.every((n) => typeof n === 'number')) {
        return `cubic-bezier(${value.join(', ')})`;
      }
      break;
    case 'fontFamily':
      if (typeof value === 'string') return quoteFamily(value);
      if (Array.isArray(value) && value.every((f) => typeof f === 'string')) {
        return (value as string[]).map(quoteFamily).join(', ');
      }
      break;
    default:
      break;
  }
  report(ctx, {
    code: 'not_expressible', severity: 'warning',
    message: `CSS has no form for this ${type || 'untyped'} value; it was omitted.`,
    details: { type, value, ...member },
  });
  return null;
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const TEXT_TRANSFORM: Record<string, string> = { original: 'none', upper: 'uppercase', lower: 'lowercase', title: 'capitalize' };
const TEXT_DECORATION: Record<string, string> = { none: 'none', underline: 'underline', strikethrough: 'line-through' };

/** `$value` members a typography leaf may carry, each its own custom property. */
const TYPOGRAPHY_MEMBERS: ReadonlyArray<readonly [key: string, type: string]> = [
  ['fontFamily', 'fontFamily'],
  ['fontSize', 'dimension'],
  ['fontWeight', 'fontWeight'],
  ['lineHeight', 'number'],
  ['letterSpacing', 'dimension'],
];
/** `$extensions` members resolved through a lookup table, keyed by their CSS-facing member name. */
const TEXT_MEMBERS: ReadonlyArray<readonly [key: string, extKey: string, table: Record<string, string>]> = [
  ['textTransform', 'textCase', TEXT_TRANSFORM],
  ['textDecoration', 'textDecoration', TEXT_DECORATION],
];
/**
 * The DTCG path segments one typography leaf registers a name under: one per
 * member it will actually emit, given its own `$value` and `$extensions` --
 * the same conditions `typographyDecls` checks per member, gathered once so a
 * path is only ever registered for a member the style would emit. These are
 * ordinary paths as far as `resolveNames` is concerned: a member path that
 * collides with a token path omits both and reports `name_collision`, exactly
 * like two tokens would. The style's own path is never registered; nothing is
 * ever emitted under it. A key absent here is never emitted, so reserving a
 * name for it anyway would only ever waste a name or, worse, collide with an
 * unrelated token that could otherwise have used it.
 */
function typographyMemberKeys(value: DtcgTree, ext: DtcgTree): string[] {
  const keys: string[] = [];
  for (const [key] of TYPOGRAPHY_MEMBERS) {
    if (key in value) keys.push(key);
  }
  for (const key of ['lineHeight', 'letterSpacing'] as const) {
    if (key in value) continue; // already covered by the loop above
    const d = asRecord(ext[key]);
    if (d && typeof d.value === 'number' && typeof d.unit === 'string') keys.push(key);
  }
  for (const [key, extKey] of TEXT_MEMBERS) {
    if (typeof ext[extKey] === 'string') keys.push(key);
  }
  return keys;
}

function converted(ctx: Ctx, property: string, from: DtcgTree, to: string): void {
  report(ctx, {
    code: 'value_converted', severity: 'info',
    message: `${property} was restated from ${String(from.value)}${String(from.unit)} as ${to}.`,
    details: { property, from, to },
  });
}

/** A member the DTCG projection parked under $extensions because the format had no home for it. CSS does. */
function extensionDimension(
  ctx: Ctx, ext: DtcgTree, key: string, name: string, percentTo: (n: number) => string,
): string | null {
  const d = asRecord(ext[key]);
  if (!d || typeof d.value !== 'number' || typeof d.unit !== 'string') return null;
  if (d.unit === '%') {
    const to = percentTo(canonicalNumber(d.value / 100));
    converted(ctx, key, d, to);
    return `${name}: ${to};`;
  }
  return `${name}: ${d.value}${d.unit};`;
}

/**
 * Declarations for one typography leaf's members, plus the member paths that
 * actually got one. `names` is keyed by `${leaf.path}.${memberKey}`; a member
 * with no name (collided, or already pruned in a later fixed-point pass) is
 * skipped without a fresh report, since resolveNames already reported it.
 */
function typographyDecls(
  ctx: Ctx, leaf: Leaf, names: Map<string, string>,
): { decls: string[]; declaredPaths: string[] } {
  const decls: string[] = [];
  const declaredPaths: string[] = [];
  const value = asRecord(leaf.value) ?? {};
  const ext = leaf.ext ?? {};
  const nameFor = (key: string): string | undefined => names.get(`${leaf.path}.${key}`);

  for (const [key, type] of TYPOGRAPHY_MEMBERS) {
    if (!(key in value)) continue;
    const name = nameFor(key);
    if (name === undefined) continue; // collided; already reported by resolveNames
    const css = cssValue(ctx, type, value[key], key);
    if (css !== null) { decls.push(`${name}: ${css};`); declaredPaths.push(`${leaf.path}.${key}`); }
  }
  // A px line height could not be a DTCG multiplier; CSS states px directly.
  // A % letter spacing is a fraction of the font size, which is what em means.
  if (!('lineHeight' in value)) {
    const name = nameFor('lineHeight');
    if (name !== undefined) {
      const d = extensionDimension(ctx, ext, 'lineHeight', name, (n) => String(n));
      if (d) { decls.push(d); declaredPaths.push(`${leaf.path}.lineHeight`); }
    }
  }
  if (!('letterSpacing' in value)) {
    const name = nameFor('letterSpacing');
    if (name !== undefined) {
      const d = extensionDimension(ctx, ext, 'letterSpacing', name, (n) => `${n}em`);
      if (d) { decls.push(d); declaredPaths.push(`${leaf.path}.letterSpacing`); }
    }
  }
  for (const [key, extKey, table] of TEXT_MEMBERS) {
    const raw = ext[extKey];
    if (typeof raw !== 'string') continue;
    const name = nameFor(key);
    if (name === undefined) continue; // collided; already reported by resolveNames
    const css = table[raw];
    if (css !== undefined) {
      decls.push(`${name}: ${css};`);
      declaredPaths.push(`${leaf.path}.${key}`);
    } else {
      report(ctx, {
        code: 'not_expressible', severity: 'info',
        message: `CSS text properties have no form for ${extKey} "${raw}"; it was omitted.`,
        details: { property: extKey, value: raw },
      });
    }
  }
  return { decls, declaredPaths };
}

const SHADOW_MEMBERS: Array<[key: string, type: string]> = [
  ['offsetX', 'dimension'], ['offsetY', 'dimension'], ['blur', 'dimension'], ['spread', 'dimension'], ['color', 'color'],
];

function shadowDecl(ctx: Ctx, leaf: Leaf, name: string): string | null {
  const layers = Array.isArray(leaf.value) ? leaf.value : [];
  const omit = (reason: string, message: string): null => {
    report(ctx, { code: 'not_expressible', severity: 'warning', message, details: { reason } });
    return null;
  };
  if (layers.length === 0) return omit('no_visible_shadow', 'The style has no visible shadow, so no box-shadow was written.');
  const parts: string[] = [];
  for (const layer of layers) {
    const l = asRecord(layer);
    if (!l) return omit('layer_not_an_object', 'A shadow layer is not an object; the style was omitted.');
    const members: string[] = [];
    for (const [key, type] of SHADOW_MEMBERS) {
      if (!(key in l)) return omit(`missing_${key}`, `A shadow layer has no ${key}, which box-shadow needs; the style was omitted.`);
      const css = cssValue(ctx, type, l[key], key);
      if (css === null) return null; // already reported by cssValue
      members.push(css);
    }
    parts.push(`${l.inset === true ? 'inset ' : ''}${members.join(' ')}`);
  }
  return `${name}: ${parts.join(', ')};`;
}

// ---------------------------------------------------------------------------
// The file
// ---------------------------------------------------------------------------

// Text that may sit inside a CSS block comment. Figma collection and mode
// names are free text, so a name holding the comment terminator (asterisk,
// slash) would close the comment and turn the rest of the name into a live
// rule; a line break would split it.
const commentSafe = (text: string): string => text.replace(/\*\//g, '* /').replace(/[\r\n]+/g, ' ');

function headerText(header: OutputHeader, nameCase: NameCase): string {
  return `${CSS_HEADER_PREFIX} from library ${commentSafe(header.libraryId)}, foundation ${header.contentHash}, ${header.platform}/${header.format}/${nameCase}.\n`
    + '   Do not edit. Change the design in Figma, republish, and run spec-layer pull. */';
}

interface EmitResult {
  blocks: Map<string, string[]>;
  entries: OutputReportEntry[];
  /** Every path (token, shadow, or typography member) that got a declaration this pass. */
  declared: Set<string>;
}

/**
 * One attempt at writing every block. `names` (permanent) and `alive`
 * (this pass's fixed-point guess) are closed over by the caller, along with
 * everything else `cssOutput` needs (sources, leaves, selectors), so a
 * fixed-point retry is just another call with a smaller `alive`.
 */
function emitPass(
  sources: Source[], leavesByFile: Map<string, Leaf[]>, names: Map<string, string>, alive: Set<string>,
  root: string, template: string, modes: Record<string, string> | undefined,
): EmitResult {
  const entries: OutputReportEntry[] = [];
  const declared = new Set<string>();
  const blocks = new Map<string, string[]>();
  for (const s of sources) {
    const perCollection = modes?.[s.collection];
    const selector = s.isDefault ? root : (perCollection ?? template)
      .replace(/\{mode\}/g, modeSlug(s.file))
      .replace(/\{collection\}/g, collectionSlug(s.file));
    const decls: string[] = [];
    for (const leaf of leavesByFile.get(s.file) ?? []) {
      const ctx: Ctx = { names, alive, report: entries, path: leaf.path, ...(s.mode !== null ? { mode: s.mode } : {}) };
      if (leaf.type === 'typography') {
        const t = typographyDecls(ctx, leaf, names);
        decls.push(...t.decls);
        for (const p of t.declaredPaths) declared.add(p);
      } else {
        const name = names.get(leaf.path);
        if (name === undefined) continue; // collided; already reported by resolveNames
        if (leaf.type === 'shadow') {
          const d = shadowDecl(ctx, leaf, name);
          if (d !== null) { decls.push(d); declared.add(leaf.path); }
        } else {
          const v = cssValue(ctx, leaf.type, leaf.value);
          if (v !== null) { decls.push(`${name}: ${v};`); declared.add(leaf.path); }
        }
      }
    }
    if (decls.length === 0) continue;
    const lines = blocks.get(selector) ?? [];
    lines.push(`  /* ${commentSafe(`${s.collection}${s.mode !== null ? `, ${s.mode}` : ''}`)} */`, ...decls.map((d) => `  ${d}`));
    blocks.set(selector, lines);
  }
  return { blocks, entries, declared };
}

export function cssOutput(exp: DtcgExport, header: OutputHeader, options: CssOutputOptions = {}): CssOutput {
  const nameCase = options.case ?? CSS_DEFAULTS.case;
  const root = options.root ?? CSS_DEFAULTS.root;
  const template = options.modeSelector ?? CSS_DEFAULTS.modeSelector;
  const sources = sourcesOf(exp.resolver);

  const leavesByFile = new Map<string, Leaf[]>();
  for (const s of sources) {
    if (!leavesByFile.has(s.file)) {
      const out: Leaf[] = [];
      collectLeaves(exp.files[s.file] ?? {}, [], out);
      leavesByFile.set(s.file, out);
    }
  }

  // A typography leaf never registers its own path (nothing is emitted
  // under it); it registers one path per member it will actually emit
  // instead, so a member name that collides with a token's name is caught by
  // resolveNames like any other collision, and an absent member never
  // reserves (or contests) a name it was never going to use. A shadow leaf,
  // like a plain token, registers its path.
  const candidatePaths = new Set<string>();
  for (const leaves of leavesByFile.values()) {
    for (const leaf of leaves) {
      if (leaf.type === 'typography') {
        const value = asRecord(leaf.value) ?? {};
        const ext = leaf.ext ?? {};
        for (const key of typographyMemberKeys(value, ext)) candidatePaths.add(`${leaf.path}.${key}`);
      } else {
        candidatePaths.add(leaf.path);
      }
    }
  }

  const resolved = resolveNames([...candidatePaths], exp.meta, {
    codeSyntaxKey: 'WEB', acceptDeclared: acceptCssDeclared, affix: (body) => `--${body}`, nameCase,
  });
  const names = resolved.names; // permanent: a path missing here collided, and is done
  const emit = (alive: Set<string>) => emitPass(sources, leavesByFile, names, alive, root, template, options.modes);

  // Fixed point on which names a reference may resolve through. A name
  // stops being a valid reference target the moment nothing actually
  // declares it under it; that can in turn strand whatever referenced it, so
  // shrink `alive` to exactly what got declared and try again. Every
  // non-collided leaf is attempted every pass regardless of whether its own
  // path is currently in `alive` (only *other* leaves' references check
  // that), so the pass where `alive` finally stops shrinking still carries a
  // fresh, complete set of omission reports: nothing needs to be carried
  // over from an earlier pass.
  // Pruning `alive` to a fixed point is what guarantees every var() this file
  // emits has a declaration somewhere in the file; it says nothing about
  // which selector block that declaration lands in, so a reference across
  // blocks (root reading a mode, or the reverse) is still valid CSS.
  let alive = new Set(names.keys());
  let pass = emit(alive);
  for (;;) {
    if (pass.declared.size === alive.size) break;
    alive = pass.declared;
    pass = emit(alive);
  }

  const map: Record<string, OutputMapEntry> = {};
  for (const [path, entry] of Object.entries(resolved.map)) {
    if (alive.has(path)) map[path] = entry;
  }

  const entries: OutputReportEntry[] = [...resolved.report, ...pass.entries];

  const shared = [...new Set(sources
    .filter((s) => !s.isDefault && options.modes?.[s.collection] === undefined)
    .map((s) => s.collection))].sort(compareCodeUnits);
  if (shared.length > 1) {
    for (const collection of shared) {
      entries.push({
        code: 'mode_selector_shared', severity: 'warning', path: collection,
        message: `${shared.length} collections with modes share the selector template ${template}; one attribute cannot carry both axes. Declare a selector per collection under outputs[].modes.`,
        details: { modifiers: shared, selector: template },
      });
    }
  }

  const body = [...pass.blocks].flatMap(([selector, lines]) => [`${selector} {`, ...lines, '}', '']);
  const text = `${[headerText(header, nameCase), '', ...body].join('\n').trimEnd()}\n`;
  return { text, map, report: sortReport(entries) };
}
