/**
 * CSS custom properties from a DTCG export. Spec:
 * docs/superpowers/specs/2026-09-08-repository-delivery-design.md, section 5.
 *
 * A projection of a projection: it reads the DtcgExport and never the
 * artifact, so v5 keeps one reader. It feeds no hash. Anything CSS cannot
 * state is omitted and reported, never approximated. Sets and every
 * modifier's default context land at the root selector; every other context
 * lands in a block under a declared selector template. Nothing about a
 * mode's name chooses a media query.
 */
import type { DtcgExport, DtcgJson, DtcgTree } from '../dtcg';
import { compareCodeUnits } from '../diagnostics';
import { canonicalNumber } from '../precision';
import {
  joinWords, pathWords, resolveNames, sortReport,
  type NameCase, type OutputMapEntry, type OutputReportEntry,
} from './naming';

export interface CssOutputOptions {
  case?: NameCase;
  /** Selector for sets and default contexts. */
  root?: string;
  /** Template for non-default contexts; `{mode}` and `{collection}` are replaced by their file-name slugs. */
  modeSelector?: string;
  /** Per-collection template, keyed by the resolver's collection label. */
  modes?: Record<string, string>;
}
export interface CssOutput { text: string; map: Record<string, OutputMapEntry>; report: OutputReportEntry[] }
export interface OutputHeader { libraryId: string; contentHash: string }

export const CSS_DEFAULTS: { case: NameCase; root: string; modeSelector: string } = {
  case: 'kebab', root: ':root', modeSelector: '[data-theme="{mode}"]',
};
/** The first bytes of every file this output writes; the CLI refuses to overwrite a file without them. */
export const CSS_HEADER_PREFIX = '/* Generated by spec-layer';
const EXT = 'com.spec-layer';

const CUSTOM_PROPERTY = /^--[A-Za-z0-9_-]+$/;
const BARE_IDENT = /^[A-Za-z_][A-Za-z0-9_-]*$/;

/** A declared WEB identifier as a custom property name, or null when it is not one. */
export function acceptCssDeclared(declared: string): string | null {
  if (CUSTOM_PROPERTY.test(declared)) return declared;
  if (BARE_IDENT.test(declared)) return `--${declared}`;
  return null;
}

// ---------------------------------------------------------------------------
// Reading the export
// ---------------------------------------------------------------------------

interface Leaf { path: string; type: string; value: DtcgJson; ext: DtcgTree | null }

const asRecord = (v: DtcgJson | undefined): DtcgTree | null =>
  (typeof v === 'object' && v !== null && !Array.isArray(v) ? v : null);

function collectLeaves(tree: DtcgJson, prefix: string[], out: Leaf[]): void {
  const node = asRecord(tree);
  if (!node) return;
  if ('$value' in node) {
    const ours = asRecord(asRecord(node.$extensions)?.[EXT]);
    out.push({
      path: prefix.join('.'), type: typeof node.$type === 'string' ? node.$type : '',
      value: node.$value, ext: ours,
    });
    return;
  }
  // Trees arrive key-sorted from sortTree, so this walk is deterministic.
  for (const key of Object.keys(node)) {
    if (key.startsWith('$')) continue;
    collectLeaves(node[key], [...prefix, key], out);
  }
}

interface Source { collection: string; mode: string | null; file: string; isDefault: boolean }

const unpointer = (s: string): string => s.replace(/~1/g, '/').replace(/~0/g, '~');
const refFile = (src: DtcgJson): string | null => {
  const r = asRecord(src);
  return r && typeof r.$ref === 'string' ? r.$ref : null;
};

/** Every file the resolver names, in resolution order, with what it stands for. */
function sourcesOf(resolver: DtcgExport['resolver']): Source[] {
  const out: Source[] = [];
  for (const { $ref } of resolver.resolutionOrder) {
    const set = /^#\/sets\/(.+)$/.exec($ref);
    const mod = /^#\/modifiers\/(.+)$/.exec($ref);
    if (set) {
      const label = unpointer(set[1]);
      for (const src of resolver.sets[label]?.sources ?? []) {
        const file = refFile(src);
        if (file) out.push({ collection: label, mode: null, file, isDefault: true });
      }
    } else if (mod) {
      const label = unpointer(mod[1]);
      const m = resolver.modifiers[label];
      if (!m) continue;
      // A modifier with no default has no context at the root: emitting one
      // would choose a mode Figma did not state.
      for (const [context, srcs] of Object.entries(m.contexts)) {
        for (const src of srcs) {
          const file = refFile(src);
          if (file) out.push({ collection: label, mode: context, file, isDefault: context === m.default });
        }
      }
    }
  }
  return out;
}

/** `primitives.light-2.json` -> `light-2`: the mode part of the file name the DTCG projection chose. */
const modeSlug = (file: string): string => file.replace(/\.json$/, '').split('.').slice(1).join('.');
const collectionSlug = (file: string): string => file.split('.')[0];

// ---------------------------------------------------------------------------
// Values
// ---------------------------------------------------------------------------

interface Ctx { names: Map<string, string>; report: OutputReportEntry[]; path: string; mode?: string }

const REF = /^\{(.+)\}$/;

function hexChannels(hex: string): [number, number, number] {
  const at = (i: number) => parseInt(hex.slice(i, i + 2), 16);
  return [at(1), at(3), at(5)];
}
const quoteFamily = (f: string): string => `"${f.replace(/["\\]/g, '\\$&')}"`;

function report(ctx: Ctx, entry: Omit<OutputReportEntry, 'path' | 'mode'>): void {
  ctx.report.push({ ...entry, path: ctx.path, ...(ctx.mode !== undefined ? { mode: ctx.mode } : {}) });
}

/** One CSS value, or null when omitted and reported. `property` names a style member. */
function cssValue(ctx: Ctx, type: string, value: DtcgJson, property?: string): string | null {
  const member: Record<string, DtcgJson> = property !== undefined ? { property } : {};
  if (typeof value === 'string') {
    const ref = REF.exec(value);
    if (ref) {
      const name = ctx.names.get(ref[1]);
      if (name !== undefined) return `var(${name})`;
      report(ctx, {
        code: 'reference_target_omitted', severity: 'warning',
        message: `References ${ref[1]}, which this output does not emit; the value was omitted.`,
        details: { target: ref[1], ...member },
      });
      return null;
    }
  }
  switch (type) {
    case 'color': {
      if (typeof value === 'string') return value; // legacy `#rrggbb` or `#rrggbbaa`, verbatim
      const c = asRecord(value);
      if (c && typeof c.hex === 'string' && typeof c.alpha === 'number') {
        if (c.alpha === 1) return c.hex;
        const [r, g, b] = hexChannels(c.hex);
        return `rgb(${r} ${g} ${b} / ${c.alpha})`;
      }
      break;
    }
    case 'dimension':
    case 'duration': {
      if (typeof value === 'string') return value;
      const d = asRecord(value);
      if (d && typeof d.value === 'number' && typeof d.unit === 'string') return `${d.value}${d.unit}`;
      break;
    }
    case 'number':
    case 'fontWeight':
      if (typeof value === 'number') return String(value);
      break;
    case 'cubicBezier':
      if (Array.isArray(value) && value.length === 4 && value.every((n) => typeof n === 'number')) {
        return `cubic-bezier(${value.join(', ')})`;
      }
      break;
    case 'fontFamily':
      if (typeof value === 'string') return quoteFamily(value);
      if (Array.isArray(value) && value.every((f) => typeof f === 'string')) {
        return (value as string[]).map(quoteFamily).join(', ');
      }
      break;
    default:
      break;
  }
  report(ctx, {
    code: 'not_expressible', severity: 'warning',
    message: `CSS has no form for this ${type || 'untyped'} value; it was omitted.`,
    details: { type, value, ...member },
  });
  return null;
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const TEXT_TRANSFORM: Record<string, string> = { original: 'none', upper: 'uppercase', lower: 'lowercase', title: 'capitalize' };
const TEXT_DECORATION: Record<string, string> = { none: 'none', underline: 'underline', strikethrough: 'line-through' };
const TYPOGRAPHY_MEMBERS: Array<[key: string, suffix: string[], type: string]> = [
  ['fontFamily', ['font', 'family'], 'fontFamily'],
  ['fontSize', ['font', 'size'], 'dimension'],
  ['fontWeight', ['font', 'weight'], 'fontWeight'],
  ['lineHeight', ['line', 'height'], 'number'],
  ['letterSpacing', ['letter', 'spacing'], 'dimension'],
];

function converted(ctx: Ctx, property: string, from: DtcgTree, to: string): void {
  report(ctx, {
    code: 'value_converted', severity: 'info',
    message: `${property} was restated from ${String(from.value)}${String(from.unit)} as ${to}.`,
    details: { property, from, to },
  });
}

/** Members the DTCG projection parked under $extensions because the format had no home for them. CSS does. */
function extensionDimension(
  ctx: Ctx, ext: DtcgTree, key: string, suffix: string[], member: (s: string[]) => string, percentTo: (n: number) => string,
): string | null {
  const d = asRecord(ext[key]);
  if (!d || typeof d.value !== 'number' || typeof d.unit !== 'string') return null;
  if (d.unit === '%') {
    const to = percentTo(canonicalNumber(d.value / 100));
    converted(ctx, key, d, to);
    return `${member(suffix)}: ${to};`;
  }
  return `${member(suffix)}: ${d.value}${d.unit};`;
}

function typographyDecls(ctx: Ctx, leaf: Leaf, member: (suffix: string[]) => string): string[] {
  const decls: string[] = [];
  const value = asRecord(leaf.value) ?? {};
  for (const [key, suffix, type] of TYPOGRAPHY_MEMBERS) {
    if (!(key in value)) continue;
    const css = cssValue(ctx, type, value[key], key);
    if (css !== null) decls.push(`${member(suffix)}: ${css};`);
  }
  const ext = leaf.ext ?? {};
  // A px line height could not be a DTCG multiplier; CSS states px directly.
  // A % letter spacing is a fraction of the font size, which is what em means.
  if (!('lineHeight' in value)) {
    const d = extensionDimension(ctx, ext, 'lineHeight', ['line', 'height'], member, (n) => String(n));
    if (d) decls.push(d);
  }
  if (!('letterSpacing' in value)) {
    const d = extensionDimension(ctx, ext, 'letterSpacing', ['letter', 'spacing'], member, (n) => `${n}em`);
    if (d) decls.push(d);
  }
  const tables: Array<[string, string[], Record<string, string>]> = [
    ['textCase', ['text', 'transform'], TEXT_TRANSFORM],
    ['textDecoration', ['text', 'decoration'], TEXT_DECORATION],
  ];
  for (const [key, suffix, table] of tables) {
    const raw = ext[key];
    if (typeof raw !== 'string') continue;
    const css = table[raw];
    if (css !== undefined) {
      decls.push(`${member(suffix)}: ${css};`);
    } else {
      report(ctx, {
        code: 'not_expressible', severity: 'info',
        message: `CSS text properties have no form for ${key} "${raw}"; it was omitted.`,
        details: { property: key, value: raw },
      });
    }
  }
  return decls;
}

const SHADOW_MEMBERS: Array<[key: string, type: string]> = [
  ['offsetX', 'dimension'], ['offsetY', 'dimension'], ['blur', 'dimension'], ['spread', 'dimension'], ['color', 'color'],
];

function shadowDecl(ctx: Ctx, leaf: Leaf, name: string): string | null {
  const layers = Array.isArray(leaf.value) ? leaf.value : [];
  const omit = (reason: string, message: string): null => {
    report(ctx, { code: 'not_expressible', severity: 'warning', message, details: { reason } });
    return null;
  };
  if (layers.length === 0) return omit('no_visible_shadow', 'The style has no visible shadow, so no box-shadow was written.');
  const parts: string[] = [];
  for (const layer of layers) {
    const l = asRecord(layer);
    if (!l) return omit('layer_not_an_object', 'A shadow layer is not an object; the style was omitted.');
    const members: string[] = [];
    for (const [key, type] of SHADOW_MEMBERS) {
      if (!(key in l)) return omit(`missing_${key}`, `A shadow layer has no ${key}, which box-shadow needs; the style was omitted.`);
      const css = cssValue(ctx, type, l[key], key);
      if (css === null) return null; // already reported by cssValue
      members.push(css);
    }
    parts.push(`${l.inset === true ? 'inset ' : ''}${members.join(' ')}`);
  }
  return `${name}: ${parts.join(', ')};`;
}

// ---------------------------------------------------------------------------
// The file
// ---------------------------------------------------------------------------

function headerText(header: OutputHeader, nameCase: NameCase): string {
  return `${CSS_HEADER_PREFIX} from library ${header.libraryId}, foundation ${header.contentHash}, web/css/${nameCase}.\n`
    + '   Do not edit. Change the design in Figma, republish, and run spec-layer pull. */';
}

export function cssOutput(exp: DtcgExport, header: OutputHeader, options: CssOutputOptions = {}): CssOutput {
  const nameCase = options.case ?? CSS_DEFAULTS.case;
  const root = options.root ?? CSS_DEFAULTS.root;
  const template = options.modeSelector ?? CSS_DEFAULTS.modeSelector;
  const sources = sourcesOf(exp.resolver);

  const leavesByFile = new Map<string, Leaf[]>();
  const paths = new Set<string>();
  for (const s of sources) {
    if (!leavesByFile.has(s.file)) {
      const out: Leaf[] = [];
      collectLeaves(exp.files[s.file] ?? {}, [], out);
      leavesByFile.set(s.file, out);
    }
    for (const leaf of leavesByFile.get(s.file) ?? []) paths.add(leaf.path);
  }

  const resolved = resolveNames([...paths], exp.meta, {
    codeSyntaxKey: 'WEB', acceptDeclared: acceptCssDeclared, affix: (body) => `--${body}`, nameCase,
  });
  const entries: OutputReportEntry[] = [...resolved.report];
  const memberOf = (path: string) => (suffix: string[]) => `--${joinWords([...pathWords(path), ...suffix], nameCase)}`;

  const blocks = new Map<string, string[]>();
  for (const s of sources) {
    const perCollection = options.modes?.[s.collection];
    const selector = s.isDefault ? root : (perCollection ?? template)
      .replace(/\{mode\}/g, modeSlug(s.file))
      .replace(/\{collection\}/g, collectionSlug(s.file));
    const decls: string[] = [];
    for (const leaf of leavesByFile.get(s.file) ?? []) {
      const name = resolved.names.get(leaf.path);
      if (name === undefined) continue; // collided; already reported
      const ctx: Ctx = { names: resolved.names, report: entries, path: leaf.path, ...(s.mode !== null ? { mode: s.mode } : {}) };
      if (leaf.type === 'typography') {
        decls.push(...typographyDecls(ctx, leaf, memberOf(leaf.path)));
      } else if (leaf.type === 'shadow') {
        const d = shadowDecl(ctx, leaf, name);
        if (d !== null) decls.push(d);
      } else {
        const v = cssValue(ctx, leaf.type, leaf.value);
        if (v !== null) decls.push(`${name}: ${v};`);
      }
    }
    if (decls.length === 0) continue;
    const lines = blocks.get(selector) ?? [];
    lines.push(`  /* ${s.collection}${s.mode !== null ? `, ${s.mode}` : ''} */`, ...decls.map((d) => `  ${d}`));
    blocks.set(selector, lines);
  }

  const shared = [...new Set(sources
    .filter((s) => !s.isDefault && options.modes?.[s.collection] === undefined)
    .map((s) => s.collection))].sort(compareCodeUnits);
  if (shared.length > 1) {
    for (const collection of shared) {
      entries.push({
        code: 'mode_selector_shared', severity: 'warning', path: collection,
        message: `${shared.length} collections with modes share the selector template ${template}; one attribute cannot carry both axes. Declare a selector per collection under outputs[].modes.`,
        details: { modifiers: shared, selector: template },
      });
    }
  }

  const body = [...blocks].flatMap(([selector, lines]) => [`${selector} {`, ...lines, '}', '']);
  const text = `${[headerText(header, nameCase), '', ...body].join('\n').trimEnd()}\n`;
  return { text, map: resolved.map, report: sortReport(entries) };
}
