import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { load } from 'js-yaml';
import type { SerializedFoundation } from '@spec-layer/extractor';

const copyText = vi.fn();
const renderManualCopyModal = vi.fn((_t: string, _notice?: string) => () => {});
vi.mock('../src/ui/clipboard', () => ({
  copyText: (t: string) => copyText(t),
  renderManualCopyModal: (t: string, notice?: string) => renderManualCopyModal(t, notice),
}));

const { copyFoundationBrief, copyFoundationBriefForScope, onFoundationMessage, setFoundationGroupDescriptions } =
  await import('../src/ui/actions');

/** Shape of the parsed brief, just deep enough for these assertions. Typed
 *  rather than `any` so a shape drift fails at compile time, matching the
 *  convention in packages/extractor/test/brief.test.ts and copyBrief.test.ts. */
interface ParsedFoundationBrief {
  spec_layer: { kind: string };
  collections: Array<{ tokens: Array<{ name: string }> }>;
  guidelines?: { origin: string; group_descriptions: Record<string, Record<string, string>> };
}

function presenter() {
  return {
    clear: vi.fn(), error: vi.fn(), info: vi.fn(),
    setBusy: vi.fn(), startProgress: vi.fn(), stopProgress: vi.fn(),
  };
}

const DUMP: SerializedFoundation = {
  fileKey: 'F1',
  extractedAt: '2026-08-14T00:00:00.000Z',
  externals: [],
  textStyles: [],
  collections: [{
    id: 'C1', name: 'Color', defaultModeId: 'm1',
    modes: [{ modeId: 'm1', name: 'Light' }],
    variables: [{
      id: 'V1', name: 'color/bg/brand', resolvedType: 'COLOR', description: '',
      codeSyntax: {}, valuesByMode: { m1: { r: 0.14, g: 0.39, b: 0.92, a: 1 } },
    }],
  }],
};

beforeEach(() => {
  copyText.mockReset().mockResolvedValue('async');
  renderManualCopyModal.mockReset();
  vi.stubGlobal('parent', { postMessage: () => {} });
});
afterEach(() => vi.unstubAllGlobals());

describe('copyFoundationBrief', () => {
  it('refuses to copy when no foundation has been read', async () => {
    const ui = presenter();
    await copyFoundationBrief(ui);
    expect(copyText).not.toHaveBeenCalled();
    expect(ui.error).toHaveBeenCalled();
  });

  it('copies parseable YAML with a foundation envelope', async () => {
    onFoundationMessage(DUMP);
    await copyFoundationBrief(presenter());
    const y = load(copyText.mock.calls[0][0]) as ParsedFoundationBrief;
    expect(y.spec_layer.kind).toBe('foundation');
    expect(y.collections[0].tokens[0].name).toBe('color/bg/brand');
  });

  it('omits guidelines when no foundation doc on canvas carries group descriptions', async () => {
    onFoundationMessage(DUMP);
    await copyFoundationBrief(presenter());
    const y = load(copyText.mock.calls[0][0]) as ParsedFoundationBrief;
    expect('guidelines' in y).toBe(false);
  });

  it('carries group descriptions merged from the foundation doc links on canvas', async () => {
    onFoundationMessage(DUMP, { Color: { 'color/bg': 'Backgrounds behind content.' } });
    await copyFoundationBrief(presenter());
    const y = load(copyText.mock.calls[0][0]) as ParsedFoundationBrief;
    expect(y.guidelines?.origin).toBe('generated');
    expect(y.guidelines?.group_descriptions).toEqual({
      Color: { 'color/bg': 'Backgrounds behind content.' },
    });
  });

  /**
   * Pins the exact sequence the review found broken: open the Foundations
   * tab (one 'foundation' reply, no docs on canvas yet, cache empty),
   * generate descriptions via "Create foundation frame(s)" (a 'foundationDone'
   * reply carrying the fresh whole-canvas merge), then Copy — with NO
   * intervening 'foundation' reply / "Refresh sources" click. Before the fix,
   * step 3's Copy read the step-1 empty cache and silently dropped the
   * descriptions the user had just generated one click earlier.
   */
  it('carries descriptions generated by a build in the same session, with no refresh in between', async () => {
    onFoundationMessage(DUMP); // 1: Foundations tab opens; nothing on canvas yet.
    setFoundationGroupDescriptions({ // 2: foundationDone lands after Create.
      Color: { 'color/bg': 'Backgrounds behind content.' },
    });
    await copyFoundationBrief(presenter()); // 3: Copy, no refresh in between.
    const y = load(copyText.mock.calls[0][0]) as ParsedFoundationBrief;
    expect(y.guidelines?.group_descriptions).toEqual({
      Color: { 'color/bg': 'Backgrounds behind content.' },
    });
  });

  /**
   * The inverse failure: a doc detached or removed from canvas must stop
   * contributing its descriptions to the very next Copy, even though the
   * last 'foundation' reply still had them cached.
   */
  it('drops descriptions once their doc is detached or removed from canvas, with no refresh in between', async () => {
    onFoundationMessage(DUMP, { Color: { 'color/bg': 'Backgrounds behind content.' } });
    setFoundationGroupDescriptions({}); // docDetached/docRemoved's fresh, now-empty merge.
    await copyFoundationBrief(presenter());
    const y = load(copyText.mock.calls[0][0]) as ParsedFoundationBrief;
    expect('guidelines' in y).toBe(false);
  });

  it('renders no caveat in the tier-3 modal for a small payload', async () => {
    onFoundationMessage(DUMP);
    copyText.mockResolvedValue('manual');
    await copyFoundationBrief(presenter());
    expect(renderManualCopyModal).toHaveBeenCalledWith(expect.any(String), undefined);
  });

  it('carries the same size caveat into the tier-3 modal as the toast reports', async () => {
    const bigDump: SerializedFoundation = {
      ...DUMP,
      collections: [{
        id: 'C1', name: 'Color', defaultModeId: 'm1',
        modes: [{ modeId: 'm1', name: 'Light' }],
        // Each variable now renders as a single flow-style line (task 5), so the
        // line count needed to cross the 800-line "large payload" threshold in
        // ui/actions.ts is roughly 1-per-variable rather than the ~4-5 it used to
        // take in block style. 900 keeps this comfortably over the threshold.
        variables: Array.from({ length: 900 }, (_, i) => ({
          id: `V${i}`, name: `color/bg/brand-${i}`, resolvedType: 'COLOR' as const, description: '',
          codeSyntax: {}, valuesByMode: { m1: { r: 0.14, g: 0.39, b: 0.92, a: 1 } },
        })),
      }],
    };
    onFoundationMessage(bigDump);
    copyText.mockResolvedValue('manual');
    await copyFoundationBrief(presenter());
    expect(renderManualCopyModal).toHaveBeenCalledTimes(1);
    const [, notice] = renderManualCopyModal.mock.calls[0];
    expect(notice).toMatch(/lines, which is large for some chat windows\.$/);
  });
});

describe('copyFoundationBriefForScope', () => {
  /** Two collections plus a text style, so narrowing has something to drop. */
  const TWO: SerializedFoundation = {
    fileKey: 'F1',
    extractedAt: '2026-08-24T00:00:00.000Z',
    externals: [],
    textStyles: [{
      name: 'heading/lg', description: '', fontFamily: 'Inter', fontStyle: 'Regular',
      fontSize: 32, lineHeight: { unit: 'AUTO' },
      letterSpacing: { unit: 'PIXELS', value: 0 }, paragraphSpacing: 0,
      paragraphIndent: 0, textCase: 'ORIGINAL', textDecoration: 'NONE',
      boundVariables: {},
    }],
    collections: [
      {
        id: 'C1', name: 'Color', defaultModeId: 'm1',
        modes: [{ modeId: 'm1', name: 'Light' }],
        variables: [{
          id: 'V1', name: 'color/bg/brand', resolvedType: 'COLOR', description: '',
          codeSyntax: {}, valuesByMode: { m1: { r: 0.14, g: 0.39, b: 0.92, a: 1 } },
        }],
      },
      {
        id: 'C2', name: 'Spacing', defaultModeId: 'n1',
        modes: [{ modeId: 'n1', name: 'Value' }],
        variables: [{
          id: 'V2', name: 'space/gap', resolvedType: 'FLOAT', description: '',
          codeSyntax: {}, valuesByMode: { n1: 8 },
        }],
      },
    ],
  };

  const COLOR_SCOPE = {
    target: 'collection' as const, collectionId: 'C1',
    collectionName: 'Color', modeIds: ['m1'],
  };

  function parse(): ParsedFoundationBrief {
    return load(copyText.mock.calls[0][0] as string) as ParsedFoundationBrief;
  }

  it('copies only the scoped collection', async () => {
    onFoundationMessage(TWO);
    const ui = presenter();
    await copyFoundationBriefForScope(COLOR_SCOPE, ui);
    const brief = parse();
    expect(brief.collections).toHaveLength(1);
    expect(brief.collections[0].tokens.map((t) => t.name)).toEqual(['color/bg/brand']);
    expect(ui.info).toHaveBeenCalled();
    expect(ui.error).not.toHaveBeenCalled();
  });

  it('ignores the group and mode narrowing the scope carries', async () => {
    onFoundationMessage(TWO);
    await copyFoundationBriefForScope(
      { ...COLOR_SCOPE, group: 'nonexistent', modeIds: [] },
      presenter(),
    );
    const brief = parse();
    expect(brief.collections[0].tokens.map((t) => t.name)).toEqual(['color/bg/brand']);
  });

  it('copies every text style for a text styles scope', async () => {
    onFoundationMessage(TWO);
    await copyFoundationBriefForScope({ target: 'textStyles' }, presenter());
    const brief = parse();
    expect(brief.collections).toEqual([]);
  });

  it('passes only the scoped collection\'s group descriptions', async () => {
    onFoundationMessage(TWO);
    setFoundationGroupDescriptions({
      Color: { color: 'Surface and text colours.' },
      Spacing: { space: 'The 8px scale.' },
    });
    await copyFoundationBriefForScope(COLOR_SCOPE, presenter());
    const brief = parse();
    expect(brief.guidelines?.group_descriptions).toEqual({
      Color: { color: 'Surface and text colours.' },
    });
  });

  it('refuses when no foundation has been read', async () => {
    // A fresh module instance, so this case sees the null spec a real cold
    // start has. The alternative — a reset helper exported from actions.ts —
    // would put test scaffolding in production code for one assertion.
    vi.resetModules();
    const fresh = await import('../src/ui/actions');
    const ui = presenter();
    await fresh.copyFoundationBriefForScope(COLOR_SCOPE, ui);
    expect(copyText).not.toHaveBeenCalled();
    expect(ui.error).toHaveBeenCalledWith(
      "Still reading this file's variables. Try again in a moment.",
    );
  });

  it('refuses when the collection is gone from the file', async () => {
    onFoundationMessage(TWO);
    const ui = presenter();
    await copyFoundationBriefForScope({ ...COLOR_SCOPE, collectionId: 'GONE' }, ui);
    expect(copyText).not.toHaveBeenCalled();
    expect(ui.error).toHaveBeenCalledWith(
      'That collection is no longer in this file. Nothing was copied.',
    );
  });

  it('leaves the whole-file copy covering every collection', async () => {
    onFoundationMessage(TWO);
    await copyFoundationBrief(presenter());
    expect(parse().collections).toHaveLength(2);
  });
});
