import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import {
  defaultOutputs, outputId, outputPathProblem, parseOutput, readIndexImports, withDefaults, type OutputConfig,
} from '../src/outputs';

const WEB: OutputConfig = { platform: 'web', format: 'css', path: 'tokens', case: 'kebab' };

describe('defaults', () => {
  it('gives web a css output at the default path and other platforms nothing yet', () => {
    expect(defaultOutputs(['web'])).toEqual([WEB]);
    expect(defaultOutputs(['ios', 'android', 'flutter'])).toEqual([]);
    expect(defaultOutputs([])).toEqual([]);
  });

  it('adds a default only for platforms without an entry', () => {
    const custom: OutputConfig = { ...WEB, path: 'src/tokens', case: 'camel' };
    expect(withDefaults([custom], ['web'])).toEqual([custom]);
    expect(withDefaults([], ['web'])).toEqual([WEB]);
  });

  it('names the record files by platform and format', () => {
    expect(outputId(WEB)).toBe('web-css');
  });
});

describe('parseOutput', () => {
  it('fills the default path and case and keeps selectors', () => {
    expect(parseOutput({ platform: 'web', format: 'css' }, 0)).toEqual(WEB);
    expect(parseOutput({
      platform: 'web', format: 'css', path: 'styles/tokens', case: 'snake', root: 'html',
      modeSelector: '.{mode}', modes: { Theme: '[data-t="{mode}"]' },
    }, 0)).toEqual({
      platform: 'web', format: 'css', path: 'styles/tokens', case: 'snake', root: 'html',
      modeSelector: '.{mode}', modes: { Theme: '[data-t="{mode}"]' },
    });
  });

  it('rejects an unknown pair with the known list', () => {
    expect(() => parseOutput({ platform: 'web', format: 'scss' }, 1))
      .toThrow('speclayer.json outputs[1]: unknown platform/format "web/scss". Known: web/css.');
    expect(() => parseOutput({ platform: 'ios', format: 'swift' }, 0))
      .toThrow('unknown platform/format "ios/swift"');
  });

  it('rejects a bad case, a non-string path, and a non-object', () => {
    expect(() => parseOutput({ platform: 'web', format: 'css', case: 'Kebab' }, 0))
      .toThrow('speclayer.json outputs[0] "case" takes kebab, camel, pascal, snake, constant.');
    expect(() => parseOutput({ platform: 'web', format: 'css', path: 3 }, 0)).toThrow('"path" must be a string');
    expect(() => parseOutput('x', 2)).toThrow('speclayer.json outputs[2] must be an object.');
    expect(() => parseOutput({ platform: 'web', format: 'css', modes: { Theme: 1 } }, 0)).toThrow('"modes" must map');
  });
});

describe('outputPathProblem', () => {
  let cwd: string;
  beforeEach(() => { cwd = mkdtempSync(join(tmpdir(), 'sl-out-')); });
  afterEach(() => { rmSync(cwd, { recursive: true, force: true }); });

  it('allows a new directory inside the repository and delegates the directory rules', () => {
    expect(outputPathProblem(cwd, '.speclayer', WEB)).toBeNull();
    expect(outputPathProblem(cwd, '.speclayer', { ...WEB, path: '../tokens' }))
      .toBe('../tokens is outside this directory. Choose a path inside the repository.');
    expect(outputPathProblem(cwd, '.speclayer', { ...WEB, path: '.speclayer/web' }))
      .toBe('.speclayer/web is inside .speclayer, which pull replaces wholesale. Choose a path outside it.');
    expect(outputPathProblem(cwd, '.speclayer', WEB, ['component-specs'])).toBeNull();
    expect(outputPathProblem(cwd, '.speclayer', WEB, ['tokens/x'])).toBe('tokens and tokens/x overlap. Give each output its own directory.');
  });

  it('refuses the 0.6.0 single-file path with the two-step fix', () => {
    expect(outputPathProblem(cwd, '.speclayer', { ...WEB, path: 'spec-layer/tokens.css' })).toBe(
      'spec-layer/tokens.css names a file; spec-layer 0.7.0 writes a directory. '
      + 'Set outputs[].path to a directory, for example "tokens", delete the old file, and pull again.',
    );
    expect(outputPathProblem(cwd, '.speclayer', { ...WEB, path: 'Styles/TOKENS.CSS' })).toContain('names a file');
  });

  it('refuses a directory holding a file without the CSS header and accepts one with it', () => {
    mkdirSync(join(cwd, 'tokens'));
    writeFileSync(join(cwd, 'tokens/mine.css'), ':root { --mine: red; }\n');
    expect(outputPathProblem(cwd, '.speclayer', WEB))
      .toBe('tokens holds files spec-layer did not write. Choose another path in speclayer.json or move them.');
    writeFileSync(join(cwd, 'tokens/mine.css'), '/* Generated by spec-layer from library x */\n');
    expect(outputPathProblem(cwd, '.speclayer', WEB)).toBeNull();
  });
});

describe('readIndexImports', () => {
  let cwd: string;
  beforeEach(() => { cwd = mkdtempSync(join(tmpdir(), 'sl-idx-')); });
  afterEach(() => { rmSync(cwd, { recursive: true, force: true }); });

  it('returns null when index.css is missing', () => {
    expect(readIndexImports(cwd, WEB)).toBeNull();
  });

  it('returns the imported names in order, ignoring non-import lines', () => {
    mkdirSync(join(cwd, 'tokens'));
    writeFileSync(join(cwd, 'tokens/index.css'), [
      '/* Generated by spec-layer from library x */',
      '',
      '/* A */',
      '@import "./a.css";',
      '/* B, Dark */',
      '@import "./b.dark.css";',
      '',
    ].join('\n'));
    expect(readIndexImports(cwd, WEB)).toEqual(['a.css', 'b.dark.css']);
  });
});
