import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, rmSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import {
  defaultOutputs, outputId, outputPathProblem, parseOutput, withDefaults, writeOutputFile, type OutputConfig,
} from '../src/outputs';

const WEB: OutputConfig = { platform: 'web', format: 'css', path: 'spec-layer/tokens.css', case: 'kebab' };

describe('defaults', () => {
  it('gives web a css output at the default path and other platforms nothing yet', () => {
    expect(defaultOutputs(['web'])).toEqual([WEB]);
    expect(defaultOutputs(['ios', 'android', 'flutter'])).toEqual([]);
    expect(defaultOutputs([])).toEqual([]);
  });

  it('adds a default only for platforms without an entry', () => {
    const custom: OutputConfig = { ...WEB, path: 'src/tokens.css', case: 'camel' };
    expect(withDefaults([custom], ['web'])).toEqual([custom]);
    expect(withDefaults([], ['web'])).toEqual([WEB]);
  });

  it('names the record files by platform and format', () => {
    expect(outputId(WEB)).toBe('web-css');
  });
});

describe('parseOutput', () => {
  it('fills the default path and case and keeps selectors', () => {
    expect(parseOutput({ platform: 'web', format: 'css' }, 0)).toEqual(WEB);
    expect(parseOutput({
      platform: 'web', format: 'css', path: 'a.css', case: 'snake', root: 'html',
      modeSelector: '.{mode}', modes: { Theme: '[data-t="{mode}"]' },
    }, 0)).toEqual({
      platform: 'web', format: 'css', path: 'a.css', case: 'snake', root: 'html',
      modeSelector: '.{mode}', modes: { Theme: '[data-t="{mode}"]' },
    });
  });

  it('rejects an unknown pair with the known list', () => {
    expect(() => parseOutput({ platform: 'web', format: 'scss' }, 1))
      .toThrow('speclayer.json outputs[1]: unknown platform/format "web/scss". Known: web/css.');
    expect(() => parseOutput({ platform: 'ios', format: 'swift' }, 0))
      .toThrow('unknown platform/format "ios/swift"');
  });

  it('rejects a bad case, a non-string path, and a non-object', () => {
    expect(() => parseOutput({ platform: 'web', format: 'css', case: 'Kebab' }, 0))
      .toThrow('speclayer.json outputs[0] "case" takes kebab, camel, pascal, snake, constant.');
    expect(() => parseOutput({ platform: 'web', format: 'css', path: 3 }, 0)).toThrow('"path" must be a string');
    expect(() => parseOutput('x', 2)).toThrow('speclayer.json outputs[2] must be an object.');
    expect(() => parseOutput({ platform: 'web', format: 'css', modes: { Theme: 1 } }, 0)).toThrow('"modes" must map');
  });
});

describe('outputPathProblem and writeOutputFile', () => {
  let cwd: string;
  beforeEach(() => { cwd = mkdtempSync(join(tmpdir(), 'sl-out-')); });
  afterEach(() => { rmSync(cwd, { recursive: true, force: true }); });

  it('allows a new path inside the directory and refuses one outside or inside outDir', () => {
    expect(outputPathProblem(cwd, '.speclayer', WEB)).toBeNull();
    expect(outputPathProblem(cwd, '.speclayer', { ...WEB, path: '../tokens.css' }))
      .toBe('../tokens.css is outside this directory. Choose a path inside the repository.');
    expect(outputPathProblem(cwd, '.speclayer', { ...WEB, path: '/etc/tokens.css' })).toContain('is outside this directory');
    expect(outputPathProblem(cwd, '.speclayer', { ...WEB, path: '.speclayer/web/tokens.css' }))
      .toBe('.speclayer/web/tokens.css is inside .speclayer, which pull replaces wholesale. Choose a path outside it.');
    expect(outputPathProblem(cwd, '.speclayer', { ...WEB, path: '.speclayer' })).toContain('is inside .speclayer');
  });

  it('refuses an existing file without the header and accepts one with it', () => {
    mkdirSync(join(cwd, 'spec-layer'));
    writeFileSync(join(cwd, WEB.path), ':root { --mine: red; }\n');
    expect(outputPathProblem(cwd, '.speclayer', WEB))
      .toBe('spec-layer/tokens.css exists and was not written by spec-layer. Choose another path or remove the file.');
    writeFileSync(join(cwd, WEB.path), '/* Generated by spec-layer from library x */\n');
    expect(outputPathProblem(cwd, '.speclayer', WEB)).toBeNull();
  });

  it('writes through a .partial rename and creates parent directories', () => {
    writeOutputFile(cwd, { ...WEB, path: 'deep/er/tokens.css' }, '/* Generated by spec-layer */\n');
    expect(readFileSync(join(cwd, 'deep/er/tokens.css'), 'utf8')).toBe('/* Generated by spec-layer */\n');
    expect(existsSync(join(cwd, 'deep/er/tokens.css.partial'))).toBe(false);
  });

  it('removes the .partial file when the rename fails, and still throws', () => {
    // A directory sitting at the target path makes renameSync fail; the
    // .partial file must not be left behind for the next write to trip over.
    mkdirSync(join(cwd, 'tokens.css'));
    expect(() => writeOutputFile(cwd, { ...WEB, path: 'tokens.css' }, '/* Generated by spec-layer */\n')).toThrow();
    expect(existsSync(join(cwd, 'tokens.css.partial'))).toBe(false);
  });
});
