import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, rmSync, readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { carriesMarker, visibleDirProblem, writeVisibleDir } from '../src/visibleDir';

const CSS = '/* Generated by spec-layer';
const YAML = 'spec_layer:\n  kind: component';

describe('visibleDir', () => {
  let cwd: string;
  beforeEach(() => { cwd = mkdtempSync(join(tmpdir(), 'sl-vis-')); });
  afterEach(() => { rmSync(cwd, { recursive: true, force: true }); });

  it('carriesMarker reads only the prefix', () => {
    writeFileSync(join(cwd, 'a.css'), `${CSS} from library x */\n:root {}\n`);
    writeFileSync(join(cwd, 'b.css'), ':root {}\n');
    writeFileSync(join(cwd, 'short.css'), '/* Gen');
    expect(carriesMarker(join(cwd, 'a.css'), CSS)).toBe(true);
    expect(carriesMarker(join(cwd, 'b.css'), CSS)).toBe(false);
    expect(carriesMarker(join(cwd, 'short.css'), CSS)).toBe(false);
  });

  it('accepts a missing directory, and refuses one outside the repository, the root itself, or inside outDir', () => {
    expect(visibleDirProblem(cwd, '.speclayer', 'tokens', CSS)).toBeNull();
    expect(visibleDirProblem(cwd, '.speclayer', '../tokens', CSS)).toBe('../tokens is outside this directory. Choose a path inside the repository.');
    expect(visibleDirProblem(cwd, '.speclayer', '.', CSS)).toBe('. is outside this directory. Choose a path inside the repository.');
    expect(visibleDirProblem(cwd, '.speclayer', '.speclayer/tokens', CSS))
      .toBe('.speclayer/tokens is inside .speclayer, which pull replaces wholesale. Choose a path outside it.');
  });

  it('refuses a directory that overlaps another visible directory', () => {
    expect(visibleDirProblem(cwd, '.speclayer', 'tokens', CSS, ['tokens'])).toBe('tokens and tokens overlap. Give each output its own directory.');
    expect(visibleDirProblem(cwd, '.speclayer', 'tokens/specs', YAML, ['tokens'])).toBe('tokens/specs and tokens overlap. Give each output its own directory.');
    expect(visibleDirProblem(cwd, '.speclayer', 'tokens', CSS, ['tokens/specs'])).toBe('tokens and tokens/specs overlap. Give each output its own directory.');
    expect(visibleDirProblem(cwd, '.speclayer', 'tokens', CSS, ['component-specs'])).toBeNull();
  });

  it('refuses a file at the path, and a directory holding anything without the marker, but ignores dotfiles', () => {
    writeFileSync(join(cwd, 'tokens'), 'x');
    expect(visibleDirProblem(cwd, '.speclayer', 'tokens', CSS)).toBe('tokens exists and is not a directory. Choose another path or remove the file.');
    mkdirSync(join(cwd, 'specs'));
    writeFileSync(join(cwd, 'specs/.DS_Store'), 'junk');
    writeFileSync(join(cwd, 'specs/.gitkeep'), '');
    expect(visibleDirProblem(cwd, '.speclayer', 'specs', YAML)).toBeNull();
    writeFileSync(join(cwd, 'specs/mine.yaml'), 'name: mine\n');
    expect(visibleDirProblem(cwd, '.speclayer', 'specs', YAML)).toBe('specs holds files spec-layer did not write. Choose another path in speclayer.json or move them.');
    rmSync(join(cwd, 'specs/mine.yaml'));
    mkdirSync(join(cwd, 'specs/sub'));
    expect(visibleDirProblem(cwd, '.speclayer', 'specs', YAML)).toBe('specs holds files spec-layer did not write. Choose another path in speclayer.json or move them.');
  });

  it('accepts a directory holding only marked files', () => {
    mkdirSync(join(cwd, 'tokens'));
    writeFileSync(join(cwd, 'tokens/index.css'), `${CSS} */\n`);
    writeFileSync(join(cwd, 'tokens/base.css'), `${CSS} */\n:root {}\n`);
    expect(visibleDirProblem(cwd, '.speclayer', 'tokens', CSS)).toBeNull();
  });

  it('writes files atomically with the last file last, creating the directory', () => {
    const names = writeVisibleDir(cwd, 'deep/tokens', CSS, { 'index.css': `${CSS} i */\n`, 'a.css': `${CSS} a */\n` }, 'index.css');
    expect(names).toEqual(['a.css', 'index.css']);
    expect(readFileSync(join(cwd, 'deep/tokens/a.css'), 'utf8')).toBe(`${CSS} a */\n`);
    expect(readdirSync(join(cwd, 'deep/tokens')).sort()).toEqual(['a.css', 'index.css']);
  });

  it('removes marked files it did not write, and leaves dotfiles and the directory alone', () => {
    mkdirSync(join(cwd, 'tokens'));
    writeFileSync(join(cwd, 'tokens/stale.css'), `${CSS} old */\n`);
    writeFileSync(join(cwd, 'tokens/.gitkeep'), '');
    writeVisibleDir(cwd, 'tokens', CSS, { 'a.css': `${CSS} a */\n` });
    expect(readdirSync(join(cwd, 'tokens')).sort()).toEqual(['.gitkeep', 'a.css']);
  });

  it('writes nothing and creates no directory when there are no files and none exists', () => {
    expect(writeVisibleDir(cwd, 'component-specs', YAML, {})).toEqual([]);
    expect(existsSync(join(cwd, 'component-specs'))).toBe(false);
  });

  it('empties an existing directory of marked files when given no files', () => {
    mkdirSync(join(cwd, 'component-specs'));
    writeFileSync(join(cwd, 'component-specs/button.yaml'), `${YAML}\n`);
    writeVisibleDir(cwd, 'component-specs', YAML, {});
    expect(readdirSync(join(cwd, 'component-specs'))).toEqual([]);
  });

  it('removes the .partial file when a rename fails, and still throws', () => {
    mkdirSync(join(cwd, 'tokens/a.css'), { recursive: true });
    expect(() => writeVisibleDir(cwd, 'tokens', CSS, { 'a.css': `${CSS} */\n` })).toThrow();
    expect(existsSync(join(cwd, 'tokens/a.css.partial'))).toBe(false);
  });
});
