/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --include-runtime=false` (hash: e399b453beadb284a08bd1254b0ca983)
interface __BaseEnv_Env {
	LICENSE_CACHE: KVNamespace;
	REQUEST_RATE_LIMITER: RateLimit;
	LICENSE_RATE_LIMITER: RateLimit;
	QUOTA: DurableObjectNamespace<import("./src/index").QuotaDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "QuotaDO";
	}
	interface StagingEnv {
		LICENSE_CACHE: KVNamespace;
		REQUEST_RATE_LIMITER: RateLimit;
		LICENSE_RATE_LIMITER: RateLimit;
		QUOTA: DurableObjectNamespace<import("./src/index").QuotaDO>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}