/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --include-runtime=false` (hash: b4af2cb86e68eaddab862a57b50b517f)
interface __BaseEnv_Env {
	LICENSE_CACHE: KVNamespace;
	REQUEST_RATE_LIMITER: RateLimit;
	LICENSE_RATE_LIMITER: RateLimit;
	QUOTA: DurableObjectNamespace<import("./src/index").QuotaDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "QuotaDO";
	}
	interface StagingEnv {
		LICENSE_CACHE: KVNamespace;
		REQUEST_RATE_LIMITER: RateLimit;
		LICENSE_RATE_LIMITER: RateLimit;
		QUOTA: DurableObjectNamespace<import("./src/index").QuotaDO>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
