import { generateDocs } from './scripts/docs.mjs';
import { generateSeo } from './scripts/seo.mjs';
import { generatePages } from './scripts/pages.mjs';
import { cp, mkdir, rm } from 'node:fs/promises';
await generateDocs();
await generateSeo();
await generatePages();
await rm(new URL('./dist/', import.meta.url), { recursive: true, force: true });
await mkdir(new URL('./dist/', import.meta.url));
await cp(new URL('./public/', import.meta.url), new URL('./dist/', import.meta.url), { recursive: true });
console.log('Built static site in dist/');
